using System.Net.Http.Headers;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Portal.Menu.Application;
using Portal.Menu.Domain;
using Portal.Security.Contracts;

namespace Portal.Menu.Infrastructure;
public sealed class MenuDbContext(DbContextOptions<MenuDbContext> options) : DbContext(options)
{
 public DbSet<MenuDefinition> Menus=>Set<MenuDefinition>(); public DbSet<MenuItem> Items=>Set<MenuItem>(); public DbSet<MenuAction> Actions=>Set<MenuAction>();
 protected override void OnModelCreating(ModelBuilder m) { m.HasDefaultSchema("menu"); m.Entity<MenuDefinition>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.TenantId).HasMaxLength(64);e.Property(x=>x.ModuleCode).HasMaxLength(100);e.Property(x=>x.Name).HasMaxLength(160);e.HasIndex(x=>new{x.TenantId,x.ModuleCode}).IsUnique();}); m.Entity<MenuItem>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Code).HasMaxLength(100);e.Property(x=>x.Route).HasMaxLength(300);e.Property(x=>x.ResourceKey).HasMaxLength(160);e.Property(x=>x.PermissionCode).HasMaxLength(180);e.HasIndex(x=>new{x.MenuId,x.Code}).IsUnique();e.HasOne<MenuDefinition>().WithMany().HasForeignKey(x=>x.MenuId);}); m.Entity<MenuAction>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Code).HasMaxLength(80);e.Property(x=>x.PermissionCode).HasMaxLength(180);e.HasOne<MenuItem>().WithMany().HasForeignKey(x=>x.MenuItemId);}); Seed(m); }
 static void Seed(ModelBuilder m) { var menu=Guid.Parse("40000000-0000-0000-0000-000000000001"); m.Entity<MenuDefinition>().HasData(MenuDefinition.Seed(menu,"default","portal","Administración")); var rows=new[]{(Guid.Parse("41000000-0000-0000-0000-000000000001"),"security","Seguridad","/portal/security","shield",1,"portal.security","portal.security.manage"),(Guid.Parse("41000000-0000-0000-0000-000000000002"),"configuration","Configuración","/portal/configuration","settings",2,"portal.configuration","portal.configuration.manage"),(Guid.Parse("41000000-0000-0000-0000-000000000003"),"audit","Auditoría","/portal/audit","history",3,"portal.audit","portal.audit.read"),(Guid.Parse("41000000-0000-0000-0000-000000000004"),"notifications","Notificaciones","/portal/notifications","notifications",4,"portal.notification","portal.notification.manage")}; m.Entity<MenuItem>().HasData(rows.Select(x=>MenuItem.Seed(x.Item1,menu,null,x.Item2,x.Item3,x.Item4,x.Item5,x.Item6,x.Item7,x.Item8))); var actions=new[]{("view","Ver"),("create","Crear"),("edit","Editar"),("deactivate","Desactivar")}; var index=1; m.Entity<MenuAction>().HasData(rows.SelectMany(row=>actions.Select(a=>MenuAction.Seed(Guid.Parse($"42000000-0000-0000-0000-{index++:000000000000}"),row.Item1,a.Item1,a.Item2,row.Item8,index)))); }
}
public sealed class EfMenuStore(MenuDbContext db):IMenuStore
{ public Task<MenuDefinition?> GetMenuAsync(Guid id,CancellationToken c)=>db.Menus.SingleOrDefaultAsync(x=>x.Id==id,c); public Task<MenuDefinition?> GetMenuByModuleAsync(string t,string m,CancellationToken c)=>db.Menus.SingleOrDefaultAsync(x=>x.TenantId==t&&x.ModuleCode==m&&x.IsActive,c); public Task<MenuItem?> GetItemAsync(Guid id,CancellationToken c)=>db.Items.SingleOrDefaultAsync(x=>x.Id==id,c); public async Task<IReadOnlyCollection<MenuItem>> GetItemsAsync(Guid id,CancellationToken c)=>await db.Items.AsNoTracking().Where(x=>x.MenuId==id).ToArrayAsync(c); public Task AddAsync<T>(T v,CancellationToken c)where T:class=>db.Set<T>().AddAsync(v,c).AsTask();public Task SaveChangesAsync(CancellationToken c)=>db.SaveChangesAsync(c);}
public sealed class SecurityPermissionChecker(IHttpClientFactory clients,IHttpContextAccessor accessor):IPermissionChecker
{ public async Task<bool> HasPermissionAsync(Guid user,string resource,string action,CancellationToken ct){var client=clients.CreateClient("security");var auth=accessor.HttpContext?.Request.Headers.Authorization.ToString();if(!string.IsNullOrWhiteSpace(auth))client.DefaultRequestHeaders.Authorization=AuthenticationHeaderValue.Parse(auth);var response=await client.PostAsJsonAsync("/api/security/check-permission",new CheckPermissionRequest(user,resource,action),ct);if(!response.IsSuccessStatusCode)return false;var envelope=await response.Content.ReadFromJsonAsync<Portal.BuildingBlocks.ApiResponse<PermissionDecisionResponse>>(cancellationToken:ct);return envelope?.Data?.Allowed==true;}}
public sealed class StructuredMenuRecorder(ILogger<StructuredMenuRecorder> log):IMenuChangeRecorder{public Task RecordAsync(string a,string id,object p,string c,CancellationToken ct){log.LogInformation("Menu change {Action} {EntityId} {CorrelationId} {@Payload}",a,id,c,p);return Task.CompletedTask;}}
public static class MenuDependencyInjection
{public static IServiceCollection AddMenuFoundation(this IServiceCollection s,IConfiguration c){var db=c.GetConnectionString("MenuDb")??throw new InvalidOperationException("MenuDb is required.");s.AddDbContext<MenuDbContext>(x=>x.UseSqlServer(db));s.AddScoped<IMenuStore,EfMenuStore>();s.AddScoped<IPermissionChecker,SecurityPermissionChecker>();s.AddScoped<IMenuChangeRecorder,StructuredMenuRecorder>();s.AddScoped<MenuService>();s.AddHttpContextAccessor();s.AddHttpClient("security",x=>x.BaseAddress=new(c["Security:BaseUrl"]??"http://security-api:8080"));if(c.GetValue<bool>("Menu:InitializeDatabase"))s.AddHostedService<Initializer>();return s;}}
internal sealed class Initializer(IServiceProvider s):IHostedService{public async Task StartAsync(CancellationToken c){await using var scope=s.CreateAsyncScope();await scope.ServiceProvider.GetRequiredService<MenuDbContext>().Database.EnsureCreatedAsync(c);}public Task StopAsync(CancellationToken c)=>Task.CompletedTask;}
