using Portal.BuildingBlocks;using Portal.Configuration.Application;using Portal.Configuration.Contracts;using Portal.Configuration.Domain;using Portal.Menu.Application;using Portal.Menu.Contracts;using Portal.Menu.Domain;using Xunit;
namespace Portal.DynamicPlatform.UnitTests;
public sealed class ConfigurationTests
{
 [Fact]public async Task User_scope_wins_precedence(){var f=new CF();var user=Guid.NewGuid();await f.Add(0,null,null,"global");await f.Add(1,null,null,"tenant");await f.Add(2,"crm",null,"module");await f.Add(3,"crm",user,"user");var r=await f.Service.ResolveAsync("theme","crm",user,default);Assert.Contains("user",r.Value!.ValueJson);}
 [Fact]public async Task Module_scope_wins_without_user_override(){var f=new CF();await f.Add(0,null,null,"global");await f.Add(1,null,null,"tenant");await f.Add(2,"finance",null,"module");var r=await f.Service.ResolveAsync("theme","finance",null,default);Assert.Equal(2,r.Value!.Scope);}
 [Fact]public async Task Deactivated_configuration_is_not_resolved(){var f=new CF();var item=await f.Add(0,null,null,"global");await f.Service.SetActiveAsync(item.Id,false,"c",default);var r=await f.Service.ResolveAsync("theme",null,null,default);Assert.False(r.IsSuccess);}
 [Fact]public async Task Update_increments_version_and_records_change(){var f=new CF();var item=await f.Add(0,null,null,"a");var r=await f.Service.UpdateAsync(item.Id,new(0,"{\"v\":\"b\"}"),"c",default);Assert.Equal(2,r.Value!.Version);Assert.True(f.Recorder.Count>=3);}
 sealed class CF{public CS Store=new();public Clock Clock=new();public Recorder Recorder=new();public ConfigurationService Service;public CF(){Service=new(Store,Recorder,Clock,new CTC("default"));}public async Task<ConfigurationResponse> Add(int scope,string? module,Guid? user,string value){var r=await Service.CreateAsync(new("theme",scope,module,user,0,$"{{\"v\":\"{value}\"}}"),"c",default);await Service.SetActiveAsync(r.Value!.Id,true,"c",default);return r.Value!;}}
 sealed class CTC(string id):IPortalTenantContext{public string TenantId=>id;public bool IsExplicit=>true;}sealed class Clock:IClock{public DateTimeOffset UtcNow=>DateTimeOffset.UtcNow;}sealed class Recorder:IPlatformChangeRecorder{public int Count;public Task RecordAsync(string a,string b,string c,object d,string e,CancellationToken f){Count++;return Task.CompletedTask;}}
 sealed class CS:IConfigurationStore{public List<ConfigurationItem> Items=[];public Task<ConfigurationItem?> GetAsync(string t,Guid id,CancellationToken c)=>Task.FromResult(Items.SingleOrDefault(x=>x.TenantId==t&&x.Id==id));public Task<IReadOnlyCollection<ConfigurationItem>> FindCandidatesAsync(string t,string k,string? m,Guid? u,CancellationToken c)=>Task.FromResult<IReadOnlyCollection<ConfigurationItem>>(Items.Where(x=>x.TenantId==t&&x.Key==k&&(x.Scope<=ConfigurationScope.Tenant||(x.ModuleCode==m&&(x.Scope!=ConfigurationScope.User||x.UserId==u)))).ToArray());public Task<IReadOnlyCollection<ConfigurationItem>> GetByScopeAsync(ConfigurationScope s,string t,string? m,Guid? u,CancellationToken c)=>Task.FromResult<IReadOnlyCollection<ConfigurationItem>>(Items.Where(x=>x.TenantId==t&&x.Scope==s).ToArray());public Task AddAsync(ConfigurationItem i,CancellationToken c){Items.Add(i);return Task.CompletedTask;}public Task SaveChangesAsync(CancellationToken c)=>Task.CompletedTask;}
}
public sealed class MenuTests
{
 [Fact]public async Task Menu_is_ordered(){var f=await MF.Create();await f.Add("second",2,"portal.security");await f.Add("first",1,"portal.security");var r=await f.Service.GetByModuleAsync("portal",default);Assert.Equal("first",r.Value!.First().Code);}
 [Fact]public async Task Menu_hides_item_without_permission(){var f=await MF.Create();await f.Add("allowed",1,"portal.security");await f.Add("hidden",2,"portal.audit");f.Permissions.Allowed.Add("portal.security");var r=await f.Service.GetForUserAsync(Guid.NewGuid(),"portal",default);Assert.Single(r.Value!);Assert.Equal("allowed",r.Value!.Single().Code);}
 [Fact]public async Task Inactive_item_is_hidden(){var f=await MF.Create();var i=await f.Add("item",1,"portal.security");f.Permissions.Allowed.Add("portal.security");await f.Service.SetActiveAsync(i.Id,false,"c",default);Assert.Empty((await f.Service.GetForUserAsync(Guid.NewGuid(),"portal",default)).Value!);}
 [Fact]public async Task Changes_invoke_recorder(){var f=await MF.Create();var i=await f.Add("item",1,"portal.security");await f.Service.ReorderAsync(new([new(i.Id,null,5)]),"c",default);Assert.True(f.Recorder.Count>=3);}
 [Fact]public async Task Tenant_cannot_read_another_tenants_menu(){var a=await MF.Create("tenant-a");await a.Add("a",1,"portal.security");var b=new MF("tenant-b",a.Store);var r=await b.Service.GetByModuleAsync("portal",default);Assert.False(r.IsSuccess);}
 sealed class TC(string id):IPortalTenantContext{public string TenantId=>id;public bool IsExplicit=>true;}
 sealed class MF{public MS Store;public PC Permissions=new();public MR Recorder=new();public MenuService Service;public MF(string tenant="default",MS? store=null){Store=store??new();Service=new(Store,Permissions,Recorder,new TC(tenant));}public static async Task<MF>Create(string tenant="default"){var f=new MF(tenant);f.MenuId=(await f.Service.CreateMenuAsync(new("portal","Portal"),"c",default)).Value;return f;}public Guid MenuId;public async Task<MenuItemResponse>Add(string code,int order,string resource)=>(await Service.CreateItemAsync(new(MenuId,null,code,code,"/"+code,null,order,resource,resource+".manage",null),"c",default)).Value!;}
 sealed class PC:IPermissionChecker{public HashSet<string>Allowed=[];public Task<bool>HasPermissionAsync(Guid u,string r,string a,CancellationToken c)=>Task.FromResult(Allowed.Contains(r));}sealed class MR:IMenuChangeRecorder{public int Count;public Task RecordAsync(string a,string b,object p,string c,CancellationToken d){Count++;return Task.CompletedTask;}}
 sealed class MS:IMenuStore{public List<MenuDefinition>Menus=[];public List<MenuItem>Items=[];public Task<MenuDefinition?>GetMenuAsync(string t,Guid i,CancellationToken c)=>Task.FromResult(Menus.SingleOrDefault(x=>x.TenantId==t&&x.Id==i));public Task<MenuDefinition?>GetMenuByModuleAsync(string t,string m,CancellationToken c)=>Task.FromResult(Menus.SingleOrDefault(x=>x.TenantId==t&&x.ModuleCode==m));public Task<MenuItem?>GetItemAsync(string t,Guid i,CancellationToken c)=>Task.FromResult(Items.Where(x=>x.Id==i).Join(Menus.Where(m=>m.TenantId==t),x=>x.MenuId,m=>m.Id,(x,m)=>x).SingleOrDefault());public Task<IReadOnlyCollection<MenuItem>>GetItemsAsync(string t,Guid i,CancellationToken c)=>Task.FromResult<IReadOnlyCollection<MenuItem>>(Items.Where(x=>x.MenuId==i&&Menus.Any(m=>m.Id==x.MenuId&&m.TenantId==t)).ToArray());public Task AddAsync<T>(T v,CancellationToken c)where T:class{if(v is MenuDefinition m)Menus.Add(m);if(v is MenuItem i)Items.Add(i);return Task.CompletedTask;}public Task SaveChangesAsync(CancellationToken c)=>Task.CompletedTask;}
}
