using System.Text.Json;
using Portal.BuildingBlocks;
using Portal.Notification.Contracts;
using Portal.Notification.Domain;

namespace Portal.Notification.Application;
public interface INotificationStore
{
 Task<NotificationTemplate?> GetTemplateAsync(Guid id,CancellationToken ct); Task<NotificationTemplate?> GetTemplateByCodeAsync(string tenant,string code,CancellationToken ct); Task<IReadOnlyCollection<NotificationTemplate>> GetTemplatesAsync(string tenant,CancellationToken ct);
 Task<NotificationMessage?> GetMessageAsync(Guid id,CancellationToken ct); Task<NotificationMessage?> GetByIdempotencyKeyAsync(string tenant,string key,CancellationToken ct); Task<IReadOnlyCollection<NotificationMessage>> GetMessagesAsync(string tenant,CancellationToken ct); Task<IReadOnlyCollection<NotificationMessage>> GetDueAsync(DateTimeOffset now,int take,CancellationToken ct);
 Task AddTemplateAsync(NotificationTemplate value,CancellationToken ct); Task AddMessageAsync(NotificationMessage value,CancellationToken ct); Task SaveChangesAsync(CancellationToken ct);
}
public interface INotificationChangeRecorder { Task RecordAsync(string action,Guid id,object payload,string correlationId,CancellationToken ct); }
public interface INotificationProvider { NotificationChannel Channel { get; } string Name { get; } Task DeliverAsync(NotificationMessage message,CancellationToken ct); }

public sealed class NotificationService(INotificationStore store,INotificationChangeRecorder recorder,IClock clock)
{
 const string Tenant="default";
 public async Task<Result<TemplateResponse>> CreateTemplateAsync(CreateTemplateRequest r,string correlation,CancellationToken ct){try{if(await store.GetTemplateByCodeAsync(Tenant,r.Code,ct)!=null)return Result<TemplateResponse>.Failure("notification.template.conflict","Template code already exists.");var t=NotificationTemplate.Create(Tenant,r.Code,r.Subject,r.Body,JsonSerializer.Serialize(r.AllowedVariables),(NotificationChannel)r.DefaultChannel,clock.UtcNow);await store.AddTemplateAsync(t,ct);await store.SaveChangesAsync(ct);await recorder.RecordAsync("template.created",t.Id,new{t.Code,t.Version},correlation,ct);return Result<TemplateResponse>.Success(Map(t));}catch(Exception e)when(e is ArgumentException or JsonException){return Invalid<TemplateResponse>(e.Message);}}
 public async Task<Result<TemplateResponse>> UpdateTemplateAsync(Guid id,UpdateTemplateRequest r,string correlation,CancellationToken ct){var t=await store.GetTemplateAsync(id,ct);if(t==null)return Missing<TemplateResponse>();try{t.Update(r.Subject,r.Body,JsonSerializer.Serialize(r.AllowedVariables),(NotificationChannel)r.DefaultChannel,clock.UtcNow);await store.SaveChangesAsync(ct);await recorder.RecordAsync("template.updated",id,new{t.Code,t.Version},correlation,ct);return Result<TemplateResponse>.Success(Map(t));}catch(Exception e)when(e is ArgumentException or JsonException){return Invalid<TemplateResponse>(e.Message);}}
 public async Task<Result<TemplateResponse>> SetTemplateActiveAsync(Guid id,bool active,string correlation,CancellationToken ct){var t=await store.GetTemplateAsync(id,ct);if(t==null)return Missing<TemplateResponse>();t.SetActive(active,clock.UtcNow);await store.SaveChangesAsync(ct);await recorder.RecordAsync(active?"template.activated":"template.deactivated",id,new{t.Code,t.Version},correlation,ct);return Result<TemplateResponse>.Success(Map(t));}
 public async Task<Result<IReadOnlyCollection<TemplateResponse>>> GetTemplatesAsync(CancellationToken ct)=>Result<IReadOnlyCollection<TemplateResponse>>.Success((await store.GetTemplatesAsync(Tenant,ct)).Select(Map).ToArray());
 public Task<Result<NotificationStatusResponse>> SendAsync(SendNotificationRequest r,string correlation,CancellationToken ct)=>RequestAsync(r.TemplateCode,r.Recipients,r.Variables,r.Channel,r.IdempotencyKey,r.MetadataJson,null,correlation,ct);
 public Task<Result<NotificationStatusResponse>> ScheduleAsync(ScheduleNotificationRequest r,string correlation,CancellationToken ct)=>RequestAsync(r.TemplateCode,r.Recipients,r.Variables,r.Channel,r.IdempotencyKey,r.MetadataJson,r.ScheduledAtUtc,correlation,ct);
 async Task<Result<NotificationStatusResponse>> RequestAsync(string code,string[] recipients,Dictionary<string,string>? variables,int? channel,string key,string? metadata,DateTimeOffset? scheduled,string correlation,CancellationToken ct)
 { var existing=await store.GetByIdempotencyKeyAsync(Tenant,key,ct);if(existing!=null)return Result<NotificationStatusResponse>.Success(Map(existing));var t=await store.GetTemplateByCodeAsync(Tenant,code,ct);if(t==null)return Result<NotificationStatusResponse>.Failure("notification.template.not_found","Template was not found.");
   try{var allowed=JsonSerializer.Deserialize<string[]>(t.AllowedVariablesJson)??[];var supplied=variables??[];var unexpected=supplied.Keys.Except(allowed,StringComparer.OrdinalIgnoreCase).FirstOrDefault();if(unexpected!=null)return Invalid<NotificationStatusResponse>($"Variable '{unexpected}' is not allowed.");var subject=Render(t.Subject,supplied);var body=Render(t.Body,supplied);var m=NotificationMessage.Request(Tenant,t,channel.HasValue?(NotificationChannel)channel.Value:null,subject,body,recipients,correlation,key,metadata,clock.UtcNow,scheduled);await store.AddMessageAsync(m,ct);await store.SaveChangesAsync(ct);await recorder.RecordAsync("notification.requested",m.Id,new NotificationRequestedV1(m.Id,m.TemplateCode,correlation),correlation,ct);return Result<NotificationStatusResponse>.Success(Map(m));}catch(Exception e)when(e is ArgumentException or InvalidOperationException or JsonException){return Invalid<NotificationStatusResponse>(e.Message);} }
 public async Task<Result<NotificationStatusResponse>> GetStatusAsync(Guid id,CancellationToken ct){var m=await store.GetMessageAsync(id,ct);return m==null?Missing<NotificationStatusResponse>():Result<NotificationStatusResponse>.Success(Map(m));}
 public async Task<Result<IReadOnlyCollection<NotificationStatusResponse>>> GetMessagesAsync(CancellationToken ct)=>Result<IReadOnlyCollection<NotificationStatusResponse>>.Success((await store.GetMessagesAsync(Tenant,ct)).Select(Map).ToArray());
 public async Task<Result<NotificationStatusResponse>> RetryAsync(Guid id,string correlation,CancellationToken ct){var m=await store.GetMessageAsync(id,ct);if(m==null)return Missing<NotificationStatusResponse>();try{m.Retry(clock.UtcNow);await store.SaveChangesAsync(ct);await recorder.RecordAsync("notification.retried",id,new{m.CorrelationId},correlation,ct);return Result<NotificationStatusResponse>.Success(Map(m));}catch(InvalidOperationException e){return Invalid<NotificationStatusResponse>(e.Message);}}
 public async Task<Result<NotificationStatusResponse>> CancelAsync(Guid id,string correlation,CancellationToken ct){var m=await store.GetMessageAsync(id,ct);if(m==null)return Missing<NotificationStatusResponse>();try{m.Cancel();await store.SaveChangesAsync(ct);await recorder.RecordAsync("notification.cancelled",id,new{m.CorrelationId},correlation,ct);return Result<NotificationStatusResponse>.Success(Map(m));}catch(InvalidOperationException e){return Invalid<NotificationStatusResponse>(e.Message);}}
 static string Render(string value,IReadOnlyDictionary<string,string> variables){foreach(var pair in variables)value=value.Replace("{{"+pair.Key+"}}",pair.Value,StringComparison.OrdinalIgnoreCase);return value;}
 static TemplateResponse Map(NotificationTemplate t)=>new(t.Id,t.Code,t.Subject,t.Body,JsonSerializer.Deserialize<string[]>(t.AllowedVariablesJson)??[],(int)t.DefaultChannel,t.Version,t.IsActive);
 static NotificationStatusResponse Map(NotificationMessage m)=>new(m.Id,m.TemplateCode,(int)m.Channel,(int)m.Status,m.AttemptCount,m.CreatedAtUtc,m.ScheduledAtUtc,m.SentAtUtc,m.FailedAtUtc,m.LastError,m.CorrelationId);
 static Result<T> Missing<T>()=>Result<T>.Failure("notification.not_found","Resource was not found."); static Result<T> Invalid<T>(string error)=>Result<T>.Failure("notification.validation",error);
}

public sealed class NotificationProcessor(INotificationStore store,IEnumerable<INotificationProvider> providers,IClock clock)
{
 public async Task<int> ProcessBatchAsync(int take,int maxAttempts,TimeSpan baseDelay,CancellationToken ct){var messages=await store.GetDueAsync(clock.UtcNow,take,ct);foreach(var m in messages){m.MarkProcessing(clock.UtcNow);await store.SaveChangesAsync(ct);var p=providers.SingleOrDefault(x=>x.Channel==m.Channel);try{if(p==null)throw new InvalidOperationException($"Provider for {m.Channel} is not configured.");await p.DeliverAsync(m,ct);m.MarkSent(clock.UtcNow,p.Name);}catch(Exception e)when(!ct.IsCancellationRequested){m.MarkFailed(e.Message,p?.Name??"none",clock.UtcNow,maxAttempts,TimeSpan.FromTicks(baseDelay.Ticks*Math.Max(1,m.AttemptCount)));}await store.SaveChangesAsync(ct);}return messages.Count;}
}
