using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Portal.Notification.Application;
using Portal.Notification.Domain;

namespace Portal.Notification.Infrastructure;
public sealed class NotificationDbContext(DbContextOptions<NotificationDbContext> options):DbContext(options)
{
 public DbSet<NotificationTemplate> Templates=>Set<NotificationTemplate>(); public DbSet<NotificationMessage> Messages=>Set<NotificationMessage>(); public DbSet<NotificationRecipient> Recipients=>Set<NotificationRecipient>(); public DbSet<DeliveryAttempt> Attempts=>Set<DeliveryAttempt>();
 protected override void OnModelCreating(ModelBuilder b){b.HasDefaultSchema("notification");b.Entity<NotificationTemplate>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.TenantId).HasMaxLength(64);e.Property(x=>x.Code).HasMaxLength(160);e.Property(x=>x.Subject).HasMaxLength(240);e.Property(x=>x.Body).HasMaxLength(8000);e.HasIndex(x=>new{x.TenantId,x.Code}).IsUnique();});b.Entity<NotificationMessage>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.TenantId).HasMaxLength(64);e.Property(x=>x.IdempotencyKey).HasMaxLength(200);e.Property(x=>x.CorrelationId).HasMaxLength(128);e.Property(x=>x.Subject).HasMaxLength(240);e.Property(x=>x.Body).HasMaxLength(8000);e.Property(x=>x.LastError).HasMaxLength(1000);e.HasIndex(x=>new{x.TenantId,x.IdempotencyKey}).IsUnique();e.HasIndex(x=>new{x.Status,x.NextAttemptAtUtc});e.HasMany(x=>x.Recipients).WithOne().HasForeignKey(x=>x.MessageId).OnDelete(DeleteBehavior.Cascade);e.HasMany(x=>x.Attempts).WithOne().HasForeignKey(x=>x.MessageId).OnDelete(DeleteBehavior.Cascade);});b.Entity<NotificationRecipient>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Address).HasMaxLength(320);});b.Entity<DeliveryAttempt>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Provider).HasMaxLength(80);e.Property(x=>x.Error).HasMaxLength(1000);});}
}
public sealed class EfNotificationStore(NotificationDbContext db):INotificationStore
{
 public Task<NotificationTemplate?> GetTemplateAsync(Guid id,CancellationToken ct)=>db.Templates.SingleOrDefaultAsync(x=>x.Id==id,ct); public Task<NotificationTemplate?> GetTemplateByCodeAsync(string t,string c,CancellationToken ct)=>db.Templates.SingleOrDefaultAsync(x=>x.TenantId==t&&x.Code==c.ToLower(),ct); public async Task<IReadOnlyCollection<NotificationTemplate>> GetTemplatesAsync(string t,CancellationToken ct)=>await db.Templates.AsNoTracking().Where(x=>x.TenantId==t).OrderBy(x=>x.Code).ToArrayAsync(ct);
 public Task<NotificationMessage?> GetMessageAsync(Guid id,CancellationToken ct)=>db.Messages.Include(x=>x.Recipients).Include(x=>x.Attempts).SingleOrDefaultAsync(x=>x.Id==id,ct); public Task<NotificationMessage?> GetByIdempotencyKeyAsync(string t,string k,CancellationToken ct)=>db.Messages.AsNoTracking().SingleOrDefaultAsync(x=>x.TenantId==t&&x.IdempotencyKey==k,ct); public async Task<IReadOnlyCollection<NotificationMessage>> GetMessagesAsync(string t,CancellationToken ct)=>await db.Messages.AsNoTracking().Where(x=>x.TenantId==t).OrderByDescending(x=>x.CreatedAtUtc).Take(200).ToArrayAsync(ct); public async Task<IReadOnlyCollection<NotificationMessage>> GetDueAsync(DateTimeOffset now,int take,CancellationToken ct)=>await db.Messages.Include(x=>x.Recipients).Where(x=>(x.Status==NotificationStatus.Pending||x.Status==NotificationStatus.Failed)&&x.NextAttemptAtUtc<=now).OrderBy(x=>x.NextAttemptAtUtc).Take(take).ToArrayAsync(ct);
 public Task AddTemplateAsync(NotificationTemplate x,CancellationToken ct)=>db.Templates.AddAsync(x,ct).AsTask(); public Task AddMessageAsync(NotificationMessage x,CancellationToken ct)=>db.Messages.AddAsync(x,ct).AsTask(); public Task SaveChangesAsync(CancellationToken ct){foreach(var entry in db.ChangeTracker.Entries<DeliveryAttempt>().Where(x=>x.State==EntityState.Modified))entry.State=EntityState.Added;return db.SaveChangesAsync(ct);}
}
public sealed class StructuredChangeRecorder(ILogger<StructuredChangeRecorder> logger):INotificationChangeRecorder { public Task RecordAsync(string action,Guid id,object payload,string correlation,CancellationToken ct){logger.LogInformation("Notification change {Action} {EntityId} {CorrelationId} {@Payload}",action,id,correlation,payload);return Task.CompletedTask;} }
public sealed class DevelopmentNotificationProvider(NotificationChannel channel,string name,ILogger logger):INotificationProvider { public NotificationChannel Channel=>channel;public string Name=>name;public Task DeliverAsync(NotificationMessage m,CancellationToken ct){logger.LogInformation("Development notification {Provider} delivered {MessageId} through {Channel} to {RecipientCount} recipients; correlation {CorrelationId}",Name,m.Id,m.Channel,m.Recipients.Count,m.CorrelationId);return Task.CompletedTask;} }
public static class NotificationDependencyInjection
{
 public static IServiceCollection AddNotificationFoundation(this IServiceCollection s,IConfiguration c){var cs=c.GetConnectionString("NotificationDb")??throw new InvalidOperationException("NotificationDb is required.");s.AddDbContext<NotificationDbContext>(x=>x.UseSqlServer(cs));s.AddScoped<INotificationStore,EfNotificationStore>();s.AddScoped<INotificationChangeRecorder,StructuredChangeRecorder>();s.AddScoped<NotificationService>();s.AddScoped<NotificationProcessor>();s.AddScoped<INotificationProvider>(p=>new DevelopmentNotificationProvider(NotificationChannel.Internal,"InternalDev",p.GetRequiredService<ILogger<DevelopmentNotificationProvider>>()));s.AddScoped<INotificationProvider>(p=>new DevelopmentNotificationProvider(NotificationChannel.EmailDev,"EmailDev",p.GetRequiredService<ILogger<DevelopmentNotificationProvider>>()));s.AddScoped<INotificationProvider>(p=>new DevelopmentNotificationProvider(NotificationChannel.LogDev,"LogDev",p.GetRequiredService<ILogger<DevelopmentNotificationProvider>>()));if(c.GetValue<bool>("Notification:InitializeDatabase"))s.AddHostedService<NotificationInitializer>();return s;}
}
internal sealed class NotificationInitializer(IServiceProvider services):IHostedService
{
 public async Task StartAsync(CancellationToken ct){await using var scope=services.CreateAsyncScope();var db=scope.ServiceProvider.GetRequiredService<NotificationDbContext>();await db.Database.EnsureCreatedAsync(ct);if(await db.Templates.AnyAsync(ct))return;var now=DateTimeOffset.UtcNow;var seeds=new[]{("portal.security.user-created","User created","User {{name}} was created"),("portal.security.role-assigned","Role assigned","Role {{role}} was assigned"),("portal.configuration.changed","Configuration changed","Configuration {{key}} changed"),("portal.menu.changed","Menu changed","Menu {{menu}} changed"),("portal.notification.test","Test notification","Hello {{name}}")};foreach(var x in seeds)db.Templates.Add(NotificationTemplate.Create("default",x.Item1,x.Item2,x.Item3,System.Text.Json.JsonSerializer.Serialize(new[]{x.Item3.Contains("{{name}}")?"name":x.Item3.Contains("{{role}}")?"role":x.Item3.Contains("{{key}}")?"key":"menu"}),NotificationChannel.LogDev,now));await db.SaveChangesAsync(ct);} public Task StopAsync(CancellationToken ct)=>Task.CompletedTask;
}
